### ISSUE TITLE
AttributeError: 'module' object has no attribute 'prototype_search_with_coverage_state'

### ISSUE THREAD

**Issue by kadir-gunel** [tuzhaopeng/NMT#2]
Hello, 

I am trying to run your code but an error (written in title) occurs in train.py file.

Any idea?

B.R.

p.s. running on python2.7, theano is in the latest version.

**Comment by tuzhaopeng** [comment]
Hi,

Have you installed NMT (''python setup.py develop'') before running the code? If you installed GroundHog before on the same server, please run "python setup.py develop" to install the NMT code. If it doesn't work, maybe you can build a new Python environment (e.g., using Anaconda) and install the NMT code in the new environment.

Best,
Zhaopeng

**Comment by kadir-gunel** [comment]
Solved! It was libblas lib which is needed by scipy.
Thank you.
