### ISSUE TITLE
运行experiment/nmt/train.py时报错：TypeError

### ISSUE THREAD

**Issue by yanmengqi** [tuzhaopeng/NMT#5]
Using gpu device 0: GeForce GT 740M (CNMeM is disabled, cuDNN not available)
2018-03-07 14:59:15,233: __main__: DEBUG: State:
{'activ': 'lambda x: TT.tanh(x)',
 'adaeps': 1e-06,
 'adarho': 0.95,
 'algo': 'SGD_adadelta',
 'backward': False,
 'bias': 0.0,
 'bias_code': True,
 'bigram': True,
 'bs': 64,
 'check_first_word': True,
 'cutoff': 1.0,
 'cutoff_rescale_length': 0.0,
 'dec_rec_gater': 'lambda x: TT.nnet.sigmoid(x)',
 'dec_rec_gating': True,
 'dec_rec_layer': 'RecurrentLayer',
 'dec_rec_reseter': 'lambda x: TT.nnet.sigmoid(x)',
 'dec_rec_reseting': True,
 'decoder_stack': 1,
 'decoding_inputs': True,
 'deep_out': True,
 'dim': 1000,
 'divide_lr': 2,
 'dropout': 1.0,
 'dropout_rec': 1.0,
 'enc_rec_gater': 'lambda x: TT.nnet.sigmoid(x)',
 'enc_rec_gating': True,
 'enc_rec_layer': 'RecurrentLayer',
 'enc_rec_reseter': 'lambda x: TT.nnet.sigmoid(x)',
 'enc_rec_reseting': True,
 'encoder_stack': 1,
 'eps': 1e-10,
 'forward': False,
 'hookFreq': 20,
 'indx_word': None,
 'indx_word_target': None,
 'last_backward': False,
 'last_forward': True,
 'level': 'DEBUG',
 'loopIters': 3000000,
 'lr': 1.0,
 'maintain_coverage': False,
 'maxout_part': 2.0,
 'minerr': -1,
 'minlr': 0,
 'n_examples': 3,
 'n_samples': 3,
 'n_sym_source': None,
 'n_sym_target': None,
 'null_sym_source': None,
 'null_sym_target': None,
 'on_nan': 'raise',
 'oov': 'UNK',
 'overwrite': 1,
 'patience': 1,
 'prefix': 'phrase_',
 'rank_n_activ': 'lambda x: x',
 'rank_n_approx': 100,
 'rec_gater': 'lambda x: TT.nnet.sigmoid(x)',
 'rec_gating': True,
 'rec_layer': 'RecurrentLayer',
 'rec_reseter': 'lambda x: TT.nnet.sigmoid(x)',
 'rec_reseting': True,
 'rec_weight_init_fn': 'sample_weights_orth',
 'rec_weight_scale': 1.0,
 'reload': True,
 'reset': -1,
 'saveFreq': 10,
 'search': False,
 'seed': 1234,
 'seqlen': 30,
 'shuffle': False,
 'sort_k_batches': 10,
 'source': [None],
 'take_top': True,
 'target': [None],
 'timeStop': 44640,
 'trainFreq': 1,
 'trim_batches': True,
 'unary_activ': 'Maxout(2)',
 'unk_sym_source': 1,
 'unk_sym_target': 1,
 'use_context_gate': False,
 'use_current_context_for_context_gate': True,
 'use_decoding_state_for_context_gate': True,
 'use_infinite_loop': True,
 'use_nce': False,
 'use_previous_target_word_for_context_gate': True,
 'validFreq': 500,
 'weight_init_fn': 'sample_weights_classic',
 'weight_noise': False,
 'weight_noise_amount': 0.01,
 'weight_noise_rec': False,
 'weight_scale': 0.01,
 'word_indx': None,
 'word_indx_trgt': None}
2018-03-07 14:59:15,233: experiments.nmt.encdec: DEBUG: Create input variables
2018-03-07 14:59:15,233: experiments.nmt.encdec: DEBUG: Create encoder
2018-03-07 14:59:15,234: experiments.nmt.encdec: DEBUG: _create_embedding_layers
Traceback (most recent call last):
  File "train.py", line 100, in <module>
    main()
  File "train.py", line 81, in main
    enc_dec.build()
  File "/home/yanmengqi/下载/beifen/NMT-master/experiments/nmt/encdec.py", line 1882, in build
    self.encoder.create_layers()
  File "/home/yanmengqi/下载/beifen/NMT-master/experiments/nmt/encdec.py", line 1124, in create_layers
    self._create_embedding_layers()
  File "/home/yanmengqi/下载/beifen/NMT-master/experiments/nmt/encdec.py", line 1016, in _create_embedding_layers
    **self.default_kwargs)
  File "/home/yanmengqi/下载/beifen/NMT-master/groundhog/layers/ff_layers.py", line 174, in __init__
    self._init_params()
  File "/home/yanmengqi/下载/beifen/NMT-master/groundhog/layers/ff_layers.py", line 205, in _init_params
    self.rng)
  File "/home/yanmengqi/下载/beifen/NMT-master/groundhog/utils/utils.py", line 108, in sample_weights_classic
    sizeX = int(sizeX)
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by tuzhaopeng** [comment]
It seems you didn't feed the model inputs correctly, see:

'source': [None],
'take_top': True,
'target': [None],

source and target should be a matrix containing int numbers, which indicate the indexes of words.

**Comment by tuzhaopeng** [comment]
Please try our newly updated code, which is more clean and powerful.

**Comment by yanmengqi** [comment]
OK，i will try .thank you!

**Comment by GITJolly** [comment]
能给一下预处理数据的程序么？还有最后的格式 。Thank you very much！
