### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by acer22969** [tuzhaopeng/NMT#8]
File "/home/jimmy/Desktop/Attention-Coverage/NMT/models.py", line 496
    def run_pipeline(self, state_below, mask_below, init_context=None, c=None, c_mask=None)
                                                                                          
SyntaxError: invalid syntax

you forgot ":" sign after define function

**Comment by tuzhaopeng** [comment]
Thanks for the issue! Already fixed.
